backend/config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  resources :user_votes
  resources :events_options
  resources :feedbacks, only: [:index, :create, :destroy ]
  resources :notification_tables
  resources :voting_events
  resources :users, only:[:index, :create, :show ]
  put '/users/:id/changepassword', to: 'users#changepassword'
  get "/logged_in", to:'sessions#logged_in'
  post "/login", to: 'sessions#login'
  delete '/logout', to: 'sessions#logout'
 
  resources :candidates do
    collection do
      get 'by_voting_event/:voting_event_id', action: :by_voting_event, as: :by_voting_event
    end
  end

  resources :user_votes do
    collection do
      get 'by_event_id/:voting_event_id', action: :by_event_id, as: :by_event_id
    end
  end

  # resources :voting_events do
  # member do
  #   delete 'destroy_by_user/:user_id', action: :destroy_by_user, as: :destroy_by_user
  # end
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

backend/app/models/user_vote.rb
class UserVote < ApplicationRecord
    belongs_to :candidate
    belongs_to :voting_event
    belongs_to :user

end

backend/app/controllers/user_votes_controller.rb
# app/controllers/user_votes_controller.rb
class UserVotesController < ApplicationController
  include CurrentUserConcern
  before_action :set_user_vote, only: [:show, :edit, :update, :destroy]

  def index
    @user_votes = UserVote.all
    render json: @user_votes
  end

  def show
    render json: @user_vote
  end

  def new
    @user_vote = UserVote.new
    render json: @user_vote
  end

  # def create
  #   @user_vote = UserVote.new(user_vote_params)
  #   @user_vote.user_id = @current_user.id

  #   if @user_vote.save
  #     render json: @user_vote, status: :created
  #   else
  #     render json: @user_vote.errors, status: :unprocessable_entity
  #   end
  # end

  def create
    # puts "@current_user: #{@current_user.inspect}"
#     voting_event_id = params[:voting_event_id]
#     user_id = params[:user_id]

# # user_votes = UserVote.where(voting_event_id: voting_event_id, user_id: user_id)
#     existing_vote_event = UserVote.where(voting_event_id: voting_event_id, user_id: user_id)
#     if existing_vote_event
#       render json: {message: "You have already voted for this event"}, status: :ok
#     else
      user_vote = UserVote.new(user_vote_params)
      user_vote.user_id = user_vote_params[:user_id]
      user_vote.candidate_id = user_vote_params[:candidate_id]
      user_vote.voting_event_id= user_vote_params[:voting_event_id]
      
      if user_vote.save
        render json: user_vote, status: :created
      else
        render json: { errors: user_vote.errors.full_messages }, status: :unprocessable_entity
      end
    # end
  end

  def edit
    render json: @user_vote
  end

  def update
    @user_vote.user_id = @current_user.id

    if @user_vote.update(user_vote_params)
      render json: @user_vote
    else
      render json: @user_vote.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @user_vote.destroy
    render json: { message: "User vote was successfully destroyed" }, status: :ok
  end
  # GET /user_votes/by_event_id/:voting_event_id
  def by_event_id
    @candidates = UserVote.where(voting_event_id: params[:voting_event_id])
    render json: @candidates
  end

  private

  def set_user_vote
    @user_vote = UserVote.find(params[:id])
  end

  # def set_current_user
  #   # Assuming you have a proper authentication system that sets @current_user
  #   @current_user = current_user
  # end

  def user_vote_params
    params.require(:user_vote).permit(:candidate_id, :user_id, :voting_event_id)
  end
end

backend/app/helpers/user_votes_helper.rb
module UserVotesHelper
end

backend/app/views/user_votes/_form.html.erb
<%= form_with(model: user_vote) do |form| %>
  <% if user_vote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_vote.errors.count, "error") %> prohibited this user_vote from being saved:</h2>

      <ul>
        <% user_vote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :userName, style: "display: block" %>
    <%= form.text_field :userName %>
  </div>

  <div>
    <%= form.label :vote_id, style: "display: block" %>
    <%= form.number_field :vote_id %>
  </div>

  <div>
    <%= form.label :eventName, style: "display: block" %>
    <%= form.text_field :eventName %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/user_votes/_user_vote.html.erb
<div id="<%= dom_id user_vote %>">
  <p>
    <strong>Username:</strong>
    <%= user_vote.userName %>
  </p>

  <p>
    <strong>Vote:</strong>
    <%= user_vote.vote_id %>
  </p>

  <p>
    <strong>Eventname:</strong>
    <%= user_vote.eventName %>
  </p>

</div>

backend/app/views/user_votes/edit.html.erb
<h1>Editing user vote</h1>

<%= render "form", user_vote: @user_vote %>

<br>

<div>
  <%= link_to "Show this user vote", @user_vote %> |
  <%= link_to "Back to user votes", user_votes_path %>
</div>

backend/app/views/user_votes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User votes</h1>

<div id="user_votes">
  <% @user_votes.each do |user_vote| %>
    <%= render user_vote %>
    <p>
      <%= link_to "Show this user vote", user_vote %>
    </p>
  <% end %>
</div>

<%= link_to "New user vote", new_user_vote_path %>

backend/app/views/user_votes/new.html.erb
<h1>New user vote</h1>

<%= render "form", user_vote: @user_vote %>

<br>

<div>
  <%= link_to "Back to user votes", user_votes_path %>
</div>

backend/app/views/user_votes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_vote %>

<div>
  <%= link_to "Edit this user vote", edit_user_vote_path(@user_vote) %> |
  <%= link_to "Back to user votes", user_votes_path %>

  <%= button_to "Destroy this user vote", @user_vote, method: :delete %>
</div>