backend/config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  resources :user_votes
  resources :events_options
  resources :feedbacks, only: [:index, :create, :destroy ]
  resources :notification_tables
  resources :voting_events
  resources :users, only:[:index, :create, :show ]
  put '/users/:id/changepassword', to: 'users#changepassword'
  get "/logged_in", to:'sessions#logged_in'
  post "/login", to: 'sessions#login'
  delete '/logout', to: 'sessions#logout'
 
  resources :candidates do
    collection do
      get 'by_voting_event/:voting_event_id', action: :by_voting_event, as: :by_voting_event
    end
  end

  resources :user_votes do
    collection do
      get 'by_event_id/:voting_event_id', action: :by_event_id, as: :by_event_id
    end
  end

  # resources :voting_events do
  # member do
  #   delete 'destroy_by_user/:user_id', action: :destroy_by_user, as: :destroy_by_user
  # end
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

backend/app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :voting_event
  belongs_to :user

  validates :role, presence: true, length: { maximum: 255 }
  validates :userName, presence: true, length: { maximum: 255 }
end

backend/app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  def index
    @candidates = Candidate.all
    render json: @candidates
  end

  # GET /candidates/1
  def show
    render json: @candidate
  end

   # GET /candidates/by_voting_event/:voting_event_id
  def by_voting_event
    @candidates = Candidate.where(voting_event_id: params[:voting_event_id])
    render json: @candidates
  end

  # POST /candidates
  # def create
  #   candidate = Candidate.new(candidate_params)
  #   candidate.role = user_vote_params[:role]
  #   candidate.userName= user_vote_params[:userName]
  #   candidate.voting_event_id= user_vote_params[:voting_event_id]
  #   candidate.user_id= user_vote_params[:user_id]
    
  #   if candidate.save
  #     render json: candidate, status: :created
  #   else
  #     render json: { errors: candidate.errors.full_messages }, status: :unprocessable_entity
  #   end
  # end
  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      render json: @candidate, status: :created
    else
      render json: { errors: @candidate.errors.full_messages }, status: :unprocessable_entity
    end
  end
  # PATCH/PUT /candidates/1
  def update
    if @candidate.update(candidate_params)
      render json: @candidate
    else
      render json: { errors: @candidate.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # DELETE /candidates/1
  def destroy
    @candidate.destroy
    render json: { message: "Candidate was successfully destroyed" }, status: :ok
  end

  private

  def set_candidate
    @candidate = Candidate.find_by(params[:id])
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Candidate not found' }, status: :not_found
  end

  def candidate_params
    params.require(:candidate).permit(:role, :userName, :voting_event_id, :user_id)
  end
end

backend/app/helpers/candidates_helper.rb
module CandidatesHelper
end

backend/app/views/candidates/_candidate.html.erb
<div id="<%= dom_id candidate %>">
  <p>
    <strong>Role:</strong>
    <%= candidate.role %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= candidate.userName %>
  </p>

  <p>
    <strong>User vote:</strong>
    <%= candidate.user_vote_id %>
  </p>

  <p>
    <strong>Voting event:</strong>
    <%= candidate.voting_event_id %>
  </p>

</div>

backend/app/views/candidates/_form.html.erb
<%= form_with(model: candidate) do |form| %>
  <% if candidate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
        <% candidate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.label :userName, style: "display: block" %>
    <%= form.text_field :userName %>
  </div>

  <div>
    <%= form.label :user_vote_id, style: "display: block" %>
    <%= form.text_field :user_vote_id %>
  </div>

  <div>
    <%= form.label :voting_event_id, style: "display: block" %>
    <%= form.text_field :voting_event_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render "form", candidate: @candidate %>

<br>

<div>
  <%= link_to "Show this candidate", @candidate %> |
  <%= link_to "Back to candidates", candidates_path %>
</div>

backend/app/views/candidates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Candidates</h1>

<div id="candidates">
  <% @candidates.each do |candidate| %>
    <%= render candidate %>
    <p>
      <%= link_to "Show this candidate", candidate %>
    </p>
  <% end %>
</div>

<%= link_to "New candidate", new_candidate_path %>

backend/app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render "form", candidate: @candidate %>

<br>

<div>
  <%= link_to "Back to candidates", candidates_path %>
</div>

backend/app/views/candidates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @candidate %>

<div>
  <%= link_to "Edit this candidate", edit_candidate_path(@candidate) %> |
  <%= link_to "Back to candidates", candidates_path %>

  <%= button_to "Destroy this candidate", @candidate, method: :delete %>
</div>