backend/config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  resources :user_votes
  resources :events_options
  resources :feedbacks, only: [:index, :create, :destroy ]
  resources :notification_tables
  resources :voting_events
  resources :users, only:[:index, :create, :show ]
  put '/users/:id/changepassword', to: 'users#changepassword'
  get "/logged_in", to:'sessions#logged_in'
  post "/login", to: 'sessions#login'
  delete '/logout', to: 'sessions#logout'
 
  resources :candidates do
    collection do
      get 'by_voting_event/:voting_event_id', action: :by_voting_event, as: :by_voting_event
    end
  end

  resources :user_votes do
    collection do
      get 'by_event_id/:voting_event_id', action: :by_event_id, as: :by_event_id
    end
  end

  # resources :voting_events do
  # member do
  #   delete 'destroy_by_user/:user_id', action: :destroy_by_user, as: :destroy_by_user
  # end
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

backend/app/models/events_option.rb
class EventsOption < ApplicationRecord
  belongs_to :voting_event

  validates :options, :eventName, presence: true
end

backend/app/controllers/events_options_controller.rb
class EventsOptionsController < ApplicationController
  before_action :set_events_option, only: [:show, :edit, :update, :destroy]

  def index
    @events_options = EventsOption.all
    render json: @events_options
  end

  def show
    render json: @events_option
  end

  def new
    @events_option = EventsOption.new
  end

  def edit
  end

  def create
    @events_option = EventsOption.new(events_option_params)

    if @events_option.save
      render json: @events_option, status: :created, location: @events_option
    else
      render json: @events_option.errors, status: :unprocessable_entity
    end
  end

  def update
    if @events_option.update(events_option_params)
      render json: @events_option
    else
      render json: @events_option.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @events_option.destroy
    render json: { message: "Events option successfully deleted" }, status: :ok
  end

  private

  def set_events_option
    @events_option = EventsOption.find(params[:id])
  end

  def events_option_params
    params.require(:events_option).permit(:options, :eventName, :voting_event_id)
  end
end

backend/app/helpers/events_options_helper.rb
module EventsOptionsHelper
end

backend/app/views/events_options/_events_option.html.erb
<div id="<%= dom_id events_option %>">
  <p>
    <strong>Options:</strong>
    <%= events_option.options %>
  </p>

  <p>
    <strong>Eventname:</strong>
    <%= events_option.eventName %>
  </p>

  <p>
    <strong>Voting event:</strong>
    <%= events_option.voting_event_id %>
  </p>

</div>

backend/app/views/events_options/_form.html.erb
<%= form_with(model: events_option) do |form| %>
  <% if events_option.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(events_option.errors.count, "error") %> prohibited this events_option from being saved:</h2>

      <ul>
        <% events_option.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :options, style: "display: block" %>
    <%= form.text_field :options %>
  </div>

  <div>
    <%= form.label :eventName, style: "display: block" %>
    <%= form.text_field :eventName %>
  </div>

  <div>
    <%= form.label :voting_event_id, style: "display: block" %>
    <%= form.text_field :voting_event_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/events_options/edit.html.erb
<h1>Editing events option</h1>

<%= render "form", events_option: @events_option %>

<br>

<div>
  <%= link_to "Show this events option", @events_option %> |
  <%= link_to "Back to events options", events_options_path %>
</div>

backend/app/views/events_options/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events options</h1>

<div id="events_options">
  <% @events_options.each do |events_option| %>
    <%= render events_option %>
    <p>
      <%= link_to "Show this events option", events_option %>
    </p>
  <% end %>
</div>

<%= link_to "New events option", new_events_option_path %>

backend/app/views/events_options/new.html.erb
<h1>New events option</h1>

<%= render "form", events_option: @events_option %>

<br>

<div>
  <%= link_to "Back to events options", events_options_path %>
</div>

backend/app/views/events_options/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @events_option %>

<div>
  <%= link_to "Edit this events option", edit_events_option_path(@events_option) %> |
  <%= link_to "Back to events options", events_options_path %>

  <%= button_to "Destroy this events option", @events_option, method: :delete %>
</div>