backend/config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  resources :user_votes
  resources :events_options
  resources :feedbacks, only: [:index, :create, :destroy ]
  resources :notification_tables
  resources :voting_events
  resources :users, only:[:index, :create, :show ]
  put '/users/:id/changepassword', to: 'users#changepassword'
  get "/logged_in", to:'sessions#logged_in'
  post "/login", to: 'sessions#login'
  delete '/logout', to: 'sessions#logout'
 
  resources :candidates do
    collection do
      get 'by_voting_event/:voting_event_id', action: :by_voting_event, as: :by_voting_event
    end
  end

  resources :user_votes do
    collection do
      get 'by_event_id/:voting_event_id', action: :by_event_id, as: :by_event_id
    end
  end

  # resources :voting_events do
  # member do
  #   delete 'destroy_by_user/:user_id', action: :destroy_by_user, as: :destroy_by_user
  # end
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

backend/app/helpers/notification_tables_helper.rb
module NotificationTablesHelper
end

backend/app/views/notification_tables/_form.html.erb
<%= form_with(model: notification_table) do |form| %>
  <% if notification_table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notification_table.errors.count, "error") %> prohibited this notification_table from being saved:</h2>

      <ul>
        <% notification_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :event, style: "display: block" %>
    <%= form.text_field :event %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/notification_tables/_notification_table.html.erb
<div id="<%= dom_id notification_table %>">
  <p>
    <strong>Event:</strong>
    <%= notification_table.event %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= notification_table.message %>
  </p>

</div>

backend/app/views/notification_tables/edit.html.erb
<h1>Editing notification table</h1>

<%= render "form", notification_table: @notification_table %>

<br>

<div>
  <%= link_to "Show this notification table", @notification_table %> |
  <%= link_to "Back to notification tables", notification_tables_path %>
</div>

backend/app/views/notification_tables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notification tables</h1>

<div id="notification_tables">
  <% @notification_tables.each do |notification_table| %>
    <%= render notification_table %>
    <p>
      <%= link_to "Show this notification table", notification_table %>
    </p>
  <% end %>
</div>

<%= link_to "New notification table", new_notification_table_path %>

backend/app/views/notification_tables/new.html.erb
<h1>New notification table</h1>

<%= render "form", notification_table: @notification_table %>

<br>

<div>
  <%= link_to "Back to notification tables", notification_tables_path %>
</div>

backend/app/views/notification_tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @notification_table %>

<div>
  <%= link_to "Edit this notification table", edit_notification_table_path(@notification_table) %> |
  <%= link_to "Back to notification tables", notification_tables_path %>

  <%= button_to "Destroy this notification table", @notification_table, method: :delete %>
</div>